In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

print("Libraries imported successfully!")

Libraries imported successfully!

In [3]:
df = pd.read_csv("../data/processed/hotel_bookings.csv")
print("data loaded successfully")

data loaded successfully

In [4]:
df.head()

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,meal,country,market_segment,distribution_channel,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,reserved_room_type,assigned_room_type,booking_changes,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,C,C,3,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,C,C,4,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,0.0,0,BB,GBR,Direct,Direct,0,0,0,A,C,0,No Deposit,NaN,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,0.0,0,BB,GBR,Corporate,Corporate,0,0,0,A,A,0,No Deposit,304.0,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,NaN,0,Transient,98.0,0,1,Check-Out,2015-07-03

In [5]:
df.tail()

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,meal,country,market_segment,distribution_channel,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,reserved_room_type,assigned_room_type,booking_changes,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
119385,City Hotel,0,23,2017,August,35,30,2,5,2,0.0,0,BB,BEL,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,394.0,NaN,0,Transient,96.14,0,0,Check-Out,2017-09-06
119386,City Hotel,0,102,2017,August,35,31,2,5,3,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,9.0,NaN,0,Transient,225.43,0,2,Check-Out,2017-09-07
119387,City Hotel,0,34,2017,August,35,31,2,5,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,NaN,0,Transient,157.71,0,4,Check-Out,2017-09-07
119388,City Hotel,0,109,2017,August,35,31,2,5,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,89.0,NaN,0,Transient,104.40,0,0,Check-Out,2017-09-07
119389,City Hotel,0,205,2017,August,35,29,2,7,2,0.0,0,HB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,NaN,0,Transient,151.20,0,2,Check-Out,2017-09-07

In [6]:
df.shape

(119390, 32)

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 119390 entries, 0 to 119389
Data columns (total 32 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   hotel                           119390 non-null  str
 1   is_canceled                     119390 non-null  int64
 2   lead_time                       119390 non-null  int64
 3   arrival_date_year               119390 non-null  int64
 4   arrival_date_month              119390 non-null  str
 5   arrival_date_week_number        119390 non-null  int64
 6   arrival_date_day_of_month       119390 non-null  int64
 7   stays_in_weekend_nights         119390 non-null  int64
 8   stays_in_week_nights            119390 non-null  int64
 9   adults                          119390 non-null  int64
 10  children                        119386 non-null  float64
 11  babies                          119390 non-null  int64
 12  meal                            119390 non-null  str
 13  country                         118902 non-null  str
 14  market_segment                  119390 non-null  str
 15  distribution_channel            119390 non-null  str
 16  is_repeated_guest               119390 non-null  int64
 17  previous_cancellations          119390 non-null  int64
 18  previous_bookings_not_canceled  119390 non-null  int64
 19  reserved_room_type              119390 non-null  str
 20  assigned_room_type              119390 non-null  str
 21  booking_changes                 119390 non-null  int64
 22  deposit_type                    119390 non-null  str
 23  agent                           103050 non-null  float64
 24  company                         6797 non-null    float64
 25  days_in_waiting_list            119390 non-null  int64
 26  customer_type                   119390 non-null  str
 27  adr                             119390 non-null  float64
 28  required_car_parking_spaces     119390 non-null  int64
 29  total_of_special_requests       119390 non-null  int64
 30  reservation_status              119390 non-null  str
 31  reservation_status_date         119390 non-null  str
dtypes: float64(4), int64(16), str(12)
memory usage: 29.1 MB

In [8]:
#Data Cleaning & Feature Engineering

# 1. Convert date
df['reservation_status_date'] = pd.to_datetime(df['reservation_status_date'])

# 2. Fill children
df['children'] = df['children'].fillna(0).astype(int)

# 3. Fill country
df['country'] = df['country'].fillna('Unknown')

# 4. Handle agent
df['agent'] = df['agent'].fillna(0)

# 5. Extra useful features
df['total_guests'] = (df['adults'] + df['children'] + df['babies'])

df['total_stay_nights'] = (df['stays_in_weekend_nights'] + df['stays_in_week_nights'])

df['total_previous_bookings'] = (df['previous_cancellations'] + df['previous_bookings_not_canceled'])

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 119390 entries, 0 to 119389
Data columns (total 35 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   hotel                           119390 non-null  str
 1   is_canceled                     119390 non-null  int64
 2   lead_time                       119390 non-null  int64
 3   arrival_date_year               119390 non-null  int64
 4   arrival_date_month              119390 non-null  str
 5   arrival_date_week_number        119390 non-null  int64
 6   arrival_date_day_of_month       119390 non-null  int64
 7   stays_in_weekend_nights         119390 non-null  int64
 8   stays_in_week_nights            119390 non-null  int64
 9   adults                          119390 non-null  int64
 10  children                        119390 non-null  int64
 11  babies                          119390 non-null  int64
 12  meal                            119390 non-null  str
 13  country                         119390 non-null  str
 14  market_segment                  119390 non-null  str
 15  distribution_channel            119390 non-null  str
 16  is_repeated_guest               119390 non-null  int64
 17  previous_cancellations          119390 non-null  int64
 18  previous_bookings_not_canceled  119390 non-null  int64
 19  reserved_room_type              119390 non-null  str
 20  assigned_room_type              119390 non-null  str
 21  booking_changes                 119390 non-null  int64
 22  deposit_type                    119390 non-null  str
 23  agent                           119390 non-null  float64
 24  company                         6797 non-null    float64
 25  days_in_waiting_list            119390 non-null  int64
 26  customer_type                   119390 non-null  str
 27  adr                             119390 non-null  float64
 28  required_car_parking_spaces     119390 non-null  int64
 29  total_of_special_requests       119390 non-null  int64
 30  reservation_status              119390 non-null  str
 31  reservation_status_date         119390 non-null  datetime64[us]
 32  total_guests                    119390 non-null  int64
 33  total_stay_nights               119390 non-null  int64
 34  total_previous_bookings         119390 non-null  int64
dtypes: datetime64[us](1), float64(3), int64(20), str(11)
memory usage: 31.9 MB

In [10]:
print(df.columns.tolist())

['hotel', 'is_canceled', 'lead_time', 'arrival_date_year', 'arrival_date_month', 'arrival_date_week_number', 'arrival_date_day_of_month', 'stays_in_weekend_nights', 'stays_in_week_nights', 'adults', 'children', 'babies', 'meal', 'country', 'market_segment', 'distribution_channel', 'is_repeated_guest', 'previous_cancellations', 'previous_bookings_not_canceled', 'reserved_room_type', 'assigned_room_type', 'booking_changes', 'deposit_type', 'agent', 'company', 'days_in_waiting_list', 'customer_type', 'adr', 'required_car_parking_spaces', 'total_of_special_requests', 'reservation_status', 'reservation_status_date', 'total_guests', 'total_stay_nights', 'total_previous_bookings']

In [11]:
missing_summary = pd.DataFrame({
    "Missing Values": df.isnull().sum(),
    "Missing %": (df.isnull().mean() * 100).round(2)
})

missing_summary = (
    missing_summary[missing_summary["Missing Values"] > 0]
    .sort_values("Missing %", ascending=False)
)

missing_summary

         Missing Values  Missing %
company          112593      94.31

In [12]:
# The 'company' column contains 94.31% missing values.
# Since this project focuses on booking behavior, cancellations, pricing,
# and customer/channel analysis, the column provides limited analytical value.
# Therefore, it is removed to avoid introducing unreliable assumptions during analysis.

df = df.drop(columns="company")

In [13]:
print(f"Columns after removing company: {df.shape[1]}")

Columns after removing company: 34

In [ ]:
#Number of Duplicate rows in the dataset

duplicate_count = df.duplicated().sum()
print(f"Duplicate rows: {duplicate_count:,}")

Duplicate rows: 32,001

In [16]:
#duplicate records

df[df.duplicated(keep=False)].head(10)

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,meal,country,market_segment,distribution_channel,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,reserved_room_type,assigned_room_type,booking_changes,deposit_type,agent,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date,total_guests,total_stay_nights,total_previous_bookings
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,0,Transient,98.00,0,1,Check-Out,2015-07-03,2,2,0
5,Resort Hotel,0,14,2015,July,27,1,0,2,2,0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,0,Transient,98.00,0,1,Check-Out,2015-07-03,2,2,0
21,Resort Hotel,0,72,2015,July,27,1,2,4,2,0,0,BB,PRT,Direct,Direct,0,0,0,A,A,1,No Deposit,250.0,0,Transient,84.67,0,1,Check-Out,2015-07-07,2,6,0
22,Resort Hotel,0,72,2015,July,27,1,2,4,2,0,0,BB,PRT,Direct,Direct,0,0,0,A,A,1,No Deposit,250.0,0,Transient,84.67,0,1,Check-Out,2015-07-07,2,6,0
39,Resort Hotel,0,70,2015,July,27,2,2,3,2,0,0,HB,ROU,Direct,Direct,0,0,0,E,E,0,No Deposit,250.0,0,Transient,137.00,0,1,Check-Out,2015-07-07,2,5,0
43,Resort Hotel,0,70,2015,July,27,2,2,3,2,0,0,HB,ROU,Direct,Direct,0,0,0,E,E,0,No Deposit,250.0,0,Transient,137.00,0,1,Check-Out,2015-07-07,2,5,0
132,Resort Hotel,1,5,2015,July,28,5,1,0,2,0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,0,Transient,97.00,0,0,Canceled,2015-07-01,2,1,0
138,Resort Hotel,1,5,2015,July,28,5,1,0,2,0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,0,Transient,97.00,0,0,Canceled,2015-07-01,2,1,0
198,Resort Hotel,0,0,2015,July,28,7,0,1,1,0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,0,Transient,109.80,0,3,Check-Out,2015-07-08,1,1,0
200,Resort Hotel,0,0,2015,July,28,7,0,1,1,0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,0,Transient,109.80,0,3,Check-Out,2015-07-08,1,1,0

In [17]:
# Remove rows that are exact duplicates of another record

df = df.drop_duplicates().copy()
print(f"Rows after removing duplicates: {len(df):,}")

Rows after removing duplicates: 87,389

In [19]:
print(f"Remaining duplicate rows: {df.duplicated().sum():,}")
print("duplicates handled")

Remaining duplicate rows: 0
duplicates handled

In [20]:
# Check whether guest counts contain negative values
print("Adults below 0:", (df["adults"] < 0).sum())
print("Children below 0:", (df["children"] < 0).sum())
print("Babies below 0:", (df["babies"] < 0).sum())

Adults below 0: 0
Children below 0: 0
Babies below 0: 0

In [21]:
# Check whether booking and stay values contain negative values
print("Lead time below 0:", (df["lead_time"] < 0).sum())
print("Weekend nights below 0:", (df["stays_in_weekend_nights"] < 0).sum())
print("Week nights below 0:", (df["stays_in_week_nights"] < 0).sum())

Lead time below 0: 0
Weekend nights below 0: 0
Week nights below 0: 0

In [22]:
# Check whether the daily room rate contains negative values
print("ADR below 0:", (df["adr"] < 0).sum())

ADR below 0: 1

In [23]:
# View the booking with a negative daily rate
df[df["adr"] < 0]

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,meal,country,market_segment,distribution_channel,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,reserved_room_type,assigned_room_type,booking_changes,deposit_type,agent,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date,total_guests,total_stay_nights,total_previous_bookings
14969,Resort Hotel,0,195,2017,March,10,5,4,6,2,0,0,BB,GBR,Groups,Direct,1,0,2,A,H,2,No Deposit,273.0,0,Transient-Party,-6.38,0,0,Check-Out,2017-03-15,2,10,2

In [24]:
df.loc[df["adr"] < 0, [
    "hotel",
    "is_canceled",
    "lead_time",
    "arrival_date_year",
    "arrival_date_month",
    "adults",
    "children",
    "babies",
    "market_segment",
    "deposit_type",
    "adr",
    "reservation_status"
]]

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,adults,children,babies,market_segment,deposit_type,adr,reservation_status
14969,Resort Hotel,0,195,2017,March,2,0,0,Groups,No Deposit,-6.38,Check-Out

In [25]:
# Remove the one booking with an invalid negative room rate
df = df[df["adr"] >= 0].copy()

print(f"Rows after removing invalid ADR: {len(df):,}")

Rows after removing invalid ADR: 87,388

In [26]:
# Confirm that no negative ADR values remain
print(f"Negative ADR values: {(df['adr'] < 0).sum()}")

Negative ADR values: 0

In [27]:
# Check for bookings where no guests are recorded
zero_guest_bookings = df[
    (df["adults"] == 0) &
    (df["children"] == 0) &
    (df["babies"] == 0)
]

print(f"Bookings with zero guests: {len(zero_guest_bookings):,}")

Bookings with zero guests: 166

In [29]:
zero_guest_bookings.head(10)

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,meal,country,market_segment,distribution_channel,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,reserved_room_type,assigned_room_type,booking_changes,deposit_type,agent,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date,total_guests,total_stay_nights,total_previous_bookings
2224,Resort Hotel,0,1,2015,October,41,6,0,3,0,0,0,SC,PRT,Corporate,Corporate,0,0,0,A,I,1,No Deposit,0.0,0,Transient-Party,0.0,0,0,Check-Out,2015-10-06,0,3,0
2409,Resort Hotel,0,0,2015,October,42,12,0,0,0,0,0,SC,PRT,Corporate,Corporate,0,0,0,A,I,0,No Deposit,0.0,0,Transient,0.0,0,0,Check-Out,2015-10-12,0,0,0
3181,Resort Hotel,0,36,2015,November,47,20,1,2,0,0,0,SC,ESP,Groups,TA/TO,0,0,0,A,C,0,No Deposit,38.0,0,Transient-Party,0.0,0,0,Check-Out,2015-11-23,0,3,0
3684,Resort Hotel,0,165,2015,December,53,30,1,4,0,0,0,SC,PRT,Groups,TA/TO,0,0,0,A,A,1,No Deposit,308.0,122,Transient-Party,0.0,0,0,Check-Out,2016-01-04,0,5,0
3708,Resort Hotel,0,165,2015,December,53,30,2,4,0,0,0,SC,PRT,Groups,TA/TO,0,0,0,A,C,1,No Deposit,308.0,122,Transient-Party,0.0,0,0,Check-Out,2016-01-05,0,6,0
4127,Resort Hotel,1,0,2016,February,8,15,0,0,0,0,0,SC,Unknown,Offline TA/TO,TA/TO,0,0,0,P,P,0,No Deposit,0.0,0,Transient,0.0,0,0,Canceled,2016-02-15,0,0,0
9376,Resort Hotel,1,0,2016,November,48,21,0,0,0,0,0,SC,Unknown,Offline TA/TO,TA/TO,0,0,0,P,P,0,No Deposit,0.0,0,Group,0.0,0,0,Canceled,2016-11-21,0,0,0
31765,Resort Hotel,0,31,2016,December,53,27,2,8,0,0,0,BB,PRT,Direct,Direct,0,0,0,D,D,3,No Deposit,0.0,0,Transient,28.0,1,0,Check-Out,2017-01-06,0,10,0
32029,Resort Hotel,0,4,2017,January,2,14,0,1,0,0,0,SC,PRT,Groups,TA/TO,0,0,0,A,G,0,No Deposit,168.0,0,Transient-Party,0.0,0,0,Check-Out,2017-01-15,0,1,0
32827,Resort Hotel,0,46,2017,January,4,25,3,9,0,0,0,SC,FRA,Direct,Direct,0,0,0,A,I,8,No Deposit,0.0,0,Transient,0.0,0,0,Check-Out,2017-02-06,0,12,0

In [ ]:
# 1 --> canceled
# 0 --> not canceled
print(zero_guest_bookings["is_canceled"].value_counts())

is_canceled
0    150
1     16
Name: count, dtype: int64

In [37]:
zero_guest_bookings[
    [
        "hotel",
        "is_canceled",
        "lead_time",
        "arrival_date_year",
        "arrival_date_month",
        "adults",
        "children",
        "babies",
        "adr",
        "reservation_status"
    ]
].head(20)

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,adults,children,babies,adr,reservation_status
2224,Resort Hotel,0,1,2015,October,0,0,0,0.0,Check-Out
2409,Resort Hotel,0,0,2015,October,0,0,0,0.0,Check-Out
3181,Resort Hotel,0,36,2015,November,0,0,0,0.0,Check-Out
3684,Resort Hotel,0,165,2015,December,0,0,0,0.0,Check-Out
3708,Resort Hotel,0,165,2015,December,0,0,0,0.0,Check-Out
4127,Resort Hotel,1,0,2016,February,0,0,0,0.0,Canceled
9376,Resort Hotel,1,0,2016,November,0,0,0,0.0,Canceled
31765,Resort Hotel,0,31,2016,December,0,0,0,28.0,Check-Out
32029,Resort Hotel,0,4,2017,January,0,0,0,0.0,Check-Out
32827,Resort Hotel,0,46,2017,January,0,0,0,0.0,Check-Out
34849,Resort Hotel,0,15,2017,March,0,0,0,0.0,Check-Out
37459,Resort Hotel,0,1,2017,June,0,0,0,0.0,Check-Out
40392,City Hotel,0,132,2015,July,0,0,0,0.0,Check-Out
40922,City Hotel,0,0,2015,August,0,0,0,0.0,Check-Out
41020,City Hotel,0,0,2015,August,0,0,0,0.0,Check-Out
41056,City Hotel,0,0,2015,August,0,0,0,0.0,Check-Out
42452,City Hotel,1,1,2015,September,0,0,0,0.0,Canceled
42591,City Hotel,0,0,2015,September,0,0,0,0.0,Check-Out
42871,City Hotel,0,0,2015,September,0,0,0,0.0,Check-Out
42934,City Hotel,0,4,2015,September,0,0,0,0.0,Check-Out

In [38]:
zero_guest_bookings["reservation_status"].value_counts()

reservation_status
Check-Out    150
Canceled      15
No-Show        1
Name: count, dtype: int64

In [39]:
print("Original rows:", len(df))
print("Zero-guest rows:", len(zero_guest_bookings))
print("Percentage:", round(len(zero_guest_bookings) / len(df) * 100, 2), "%")

Original rows: 87388
Zero-guest rows: 166
Percentage: 0.19 %

In [40]:
df_clean = df[df["total_guests"] > 0].copy()

print("Original rows:", len(df))
print("Cleaned rows:", len(df_clean))
print("Rows removed:", len(df) - len(df_clean))

Original rows: 87388
Cleaned rows: 87222
Rows removed: 166

In [41]:
# Verify that no zero-guest bookings remain
print("Zero-guest bookings remaining:", (df_clean["total_guests"] == 0).sum())

Zero-guest bookings remaining: 0

In [53]:
print("total_guests <= 0:", (df_clean["total_guests"] <= 0).sum())
print("total_stay_nights < 0:", (df_clean["total_stay_nights"] < 0).sum())
print("total_previous_bookings < 0:", (df_clean["total_previous_bookings"] < 0).sum())
print("ADR < 0:", (df_clean["adr"] < 0).sum())

total_guests <= 0: 0
total_stay_nights < 0: 0
total_previous_bookings < 0: 0
ADR < 0: 0

In [54]:
df_clean.to_csv("../data/processed/hotel_bookings_clean.csv", index=False)

print("Cleaned dataset saved successfully!")

Cleaned dataset saved successfully!

In [55]:
import os

print(os.path.exists("../data/processed/hotel_bookings_clean.csv"))

True